### ISSUE TITLE
Kontorsøket: Ingen treff på lokalt NAV-kontor ved postnummersøk i byer

### ISSUE THREAD

**Issue by eivindskifjeld** [navikt/nav-office-search#66]
Der hvor det er flere NAV-kontorer i en by, vises ikke det lokale NAV-kontoret ved postnummersøk.
I tilfellet under burde NAV Nordstrand blitt vist.

![Image](https://github.com/navikt/nav-office-search/assets/39593932/9dd3b3f7-f047-4adf-81b2-0c9295e53632)

**Comment by eivindskifjeld** [comment]
Der hvor det er flere NAV-kontorer i en by, vises ikke det lokale NAV-kontoret ved postnummersøk.

![Image](https://github.com/navikt/nav-office-search/assets/39593932/9dd3b3f7-f047-4adf-81b2-0c9295e53632)

**Comment by anders-nom** [comment]
Skyldtes endring (bug?) i tpsws adressesøk (se linked PR). Lagt inn workaround som fungerer for vår use case.
